name: Docker Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update source
      run: |
        curl -s ${{ secrets.SCRIPT }} | bash -s -- > /dev/null 2>&1
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update ubuntu base
        commit_options: '--no-verify --signoff'
        repository: .
        commit_user_name: Nitesh
        commit_user_email: niteshraj231@outlook.com
        commit_author: Nitesh <niteshraj231@outlook.com>>
    - name: Build and Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nitesh231/hirsute-hippo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
